/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GuardianContact = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const PanicLog = IDL.Record({ 'timestamp' : IDL.Int });

export const idlService = IDL.Service({
  'getGuardianContact' : IDL.Func([], [GuardianContact], ['query']),
  'getPanicLog' : IDL.Func([], [IDL.Vec(PanicLog)], ['query']),
  'logPanicActivation' : IDL.Func([], [], []),
  'saveGuardianContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GuardianContact = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const PanicLog = IDL.Record({ 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'getGuardianContact' : IDL.Func([], [GuardianContact], ['query']),
    'getPanicLog' : IDL.Func([], [IDL.Vec(PanicLog)], ['query']),
    'logPanicActivation' : IDL.Func([], [], []),
    'saveGuardianContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };